# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxMXPym_H_yIQHrTnWmAaINx2Qhd17Sx
"""

import os
import tempfile
from pathlib import Path

import streamlit as st
from ultralytics import YOLO


st.set_page_config(page_title="Drone Detection", layout="wide")
st.title("🛸 Drone Detection (Video)")
st.write("ارفع فيديو، والنظام بيطلع لك فيديو عليه كشف الدرون + كلمة Drone فوقه.")

# --- Model path (best.pt next to app.py) ---
MODEL_PATH = "best.pt"

@st.cache_resource
def load_model():
    if not os.path.exists(MODEL_PATH):
        raise FileNotFoundError(
            f"❌ ما لقيت ملف المودل: {MODEL_PATH}\n"
            f"تأكد ان best.pt موجود بنفس مجلد app.py"
        )
    return YOLO(MODEL_PATH)

model = load_model()

# --- Sidebar controls ---
st.sidebar.header("⚙️ Settings")
conf_thres = st.sidebar.slider("Confidence", 0.05, 0.95, 0.30, 0.05)
iou_thres  = st.sidebar.slider("IoU", 0.05, 0.95, 0.50, 0.05)

uploaded = st.file_uploader("📤 ارفع فيديو (mp4/mov/avi)", type=["mp4", "mov", "avi", "mkv"])

if uploaded is None:
    st.info("ارفع فيديو عشان نبدأ.")
    st.stop()

# --- Save uploaded video to a temp file ---
tmp_dir = tempfile.mkdtemp()
input_path = os.path.join(tmp_dir, uploaded.name)

with open(input_path, "wb") as f:
    f.write(uploaded.getbuffer())

st.success("✅ تم رفع الفيديو")

# --- Open video ---
import cv2
cap = cv2.VideoCapture(input_path)
if not cap.isOpened():
    st.error("❌ ما قدرت أفتح الفيديو. جرّب فيديو ثاني.")
    st.stop()

fps = cap.get(cv2.CAP_PROP_FPS)
if fps is None or fps <= 0:
    fps = 30.0

width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# --- Output video path ---
output_path = os.path.join(tmp_dir, "output.mp4")

fourcc = cv2.VideoWriter_fourcc(*"mp4v")
writer = cv2.VideoWriter(output_path, fourcc, fps, (width, height))

# --- Display area ---
col1, col2 = st.columns([1, 1])
with col1:
    st.subheader("🎬 الفيديو الأصلي")
    st.video(input_path)

with col2:
    st.subheader("✅ المعالجة (يتم تجهيزها...)")
    progress = st.progress(0)
    status = st.empty()

# --- Process frames ---
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) if cap.get(cv2.CAP_PROP_FRAME_COUNT) else 0
frame_idx = 0

# If your dataset has only one class = drone, its index is usually 0
# We'll label everything as "Drone" regardless of class name in the model.
LABEL_TEXT = "Drone"

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_idx += 1

    # Predict on this frame
    results = model.predict(frame, conf=conf_thres, iou=iou_thres, verbose=False)

    # Draw boxes + label
    if results and len(results) > 0:
        r = results[0]
        if r.boxes is not None and len(r.boxes) > 0:
            for b in r.boxes:
                x1, y1, x2, y2 = map(int, b.xyxy[0].tolist())
                conf = float(b.conf[0]) if b.conf is not None else 0.0

                # Rectangle
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)

                # Label (Drone + conf)
                txt = f"{LABEL_TEXT} {conf:.2f}"
                (tw, th), _ = cv2.getTextSize(txt, cv2.FONT_HERSHEY_SIMPLEX, 0.7, 2)
                cv2.rectangle(frame, (x1, y1 - th - 10), (x1 + tw + 8, y1), (0, 255, 0), -1)
                cv2.putText(frame, txt, (x1 + 4, y1 - 6),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 0, 0), 2, cv2.LINE_AA)

    writer.write(frame)

    # Progress
    if total_frames > 0:
        p = min(frame_idx / total_frames, 1.0)
        progress.progress(int(p * 100))
        status.write(f"Processing frame {frame_idx}/{total_frames} ...")
    else:
        # fallback if frame count unknown
        if frame_idx % 30 == 0:
            status.write(f"Processing frame {frame_idx} ...")

cap.release()
writer.release()

progress.progress(100)
status.write("✅ Finished!")

# --- Show output ---
st.subheader("📌 الفيديو الناتج")
st.video(output_path)

with open(output_path, "rb") as f:
    st.download_button(
        "⬇️ Download result video",
        data=f,
        file_name="drone_detection_output.mp4",
        mime="video/mp4"
    )

st.caption("ملاحظة: إذا كان الفيديو طويل جدًا ممكن ياخذ وقت بالمعالجة على Streamlit Cloud.")
